version: "3"

services:

  db:
    build: ./db
    ports:
      - "3306:3306"
    container_name: mysql_ssl
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"

  script:
    build: .
    container_name: ssl_analyzer
    depends_on:
      - "db"